2018-10-19 11:54:36,265 ERROR: Exception on /index [GET] [in c:\users\administrator.pb1501034\microblog\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\administrator.pb1501034\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\administrator.pb1501034\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\administrator.pb1501034\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\administrator.pb1501034\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\administrator.pb1501034\microblog\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\administrator.pb1501034\microblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\administrator.pb1501034\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Administrator.PB1501034\microblog\app\routes.py", line 35, in index
    posts=posts)
  File "c:\users\administrator.pb1501034\microblog\venv\lib\site-packages\flask\templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "c:\users\administrator.pb1501034\microblog\venv\lib\site-packages\jinja2\environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "c:\users\administrator.pb1501034\microblog\venv\lib\site-packages\jinja2\environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "c:\users\administrator.pb1501034\microblog\venv\lib\site-packages\jinja2\environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "c:\users\administrator.pb1501034\microblog\venv\lib\site-packages\jinja2\loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "c:\users\administrator.pb1501034\microblog\venv\lib\site-packages\jinja2\environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "c:\users\administrator.pb1501034\microblog\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\administrator.pb1501034\microblog\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Administrator.PB1501034\microblog\app\templates\index.html", line 20, in template
    {% endblock %}
  File "c:\users\administrator.pb1501034\microblog\venv\lib\site-packages\jinja2\environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "c:\users\administrator.pb1501034\microblog\venv\lib\site-packages\jinja2\parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "c:\users\administrator.pb1501034\microblog\venv\lib\site-packages\jinja2\parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "c:\users\administrator.pb1501034\microblog\venv\lib\site-packages\jinja2\parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "c:\users\administrator.pb1501034\microblog\venv\lib\site-packages\jinja2\parser.py", line 268, in parse_block
    node.body = self.parse_statements(('name:endblock',), drop_needle=True)
  File "c:\users\administrator.pb1501034\microblog\venv\lib\site-packages\jinja2\parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "c:\users\administrator.pb1501034\microblog\venv\lib\site-packages\jinja2\parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "c:\users\administrator.pb1501034\microblog\venv\lib\site-packages\jinja2\parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "c:\users\administrator.pb1501034\microblog\venv\lib\site-packages\jinja2\parser.py", line 213, in parse_if
    'name:endif'))
  File "c:\users\administrator.pb1501034\microblog\venv\lib\site-packages\jinja2\parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "c:\users\administrator.pb1501034\microblog\venv\lib\site-packages\jinja2\parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "c:\users\administrator.pb1501034\microblog\venv\lib\site-packages\jinja2\parser.py", line 144, in parse_statement
    self.fail_unknown_tag(token.value, token.lineno)
  File "c:\users\administrator.pb1501034\microblog\venv\lib\site-packages\jinja2\parser.py", line 97, in fail_unknown_tag
    return self._fail_ut_eof(name, self._end_token_stack, lineno)
  File "c:\users\administrator.pb1501034\microblog\venv\lib\site-packages\jinja2\parser.py", line 90, in _fail_ut_eof
    self.fail(' '.join(message), lineno)
  File "c:\users\administrator.pb1501034\microblog\venv\lib\site-packages\jinja2\parser.py", line 59, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endblock'. You probably made a nesting mistake. Jinja is expecting this tag, but currently looking for 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.
2018-10-19 11:55:15,932 INFO: Microblog startup [in C:\Users\Administrator.PB1501034\microblog\app\__init__.py:30]
2018-10-19 11:57:31,089 INFO: Microblog startup [in C:\Users\Administrator.PB1501034\microblog\app\__init__.py:30]
2018-10-19 11:58:50,404 INFO: Microblog startup [in C:\Users\Administrator.PB1501034\microblog\app\__init__.py:30]
2018-10-19 14:07:04,248 INFO: Microblog startup [in C:\Users\Administrator.PB1501034\microblog\app\__init__.py:30]
2018-10-19 14:09:34,797 INFO: Microblog startup [in C:\Users\Administrator.PB1501034\microblog\app\__init__.py:30]
2018-10-19 14:27:14,544 INFO: Microblog startup [in C:\Users\Administrator.PB1501034\microblog\app\__init__.py:32]
2018-10-19 14:27:17,320 INFO: Microblog startup [in C:\Users\Administrator.PB1501034\microblog\app\__init__.py:32]
2018-10-19 14:34:35,273 INFO: Microblog startup [in C:\Users\Administrator.PB1501034\microblog\app\__init__.py:32]
2018-10-19 14:48:02,961 INFO: Microblog startup [in C:\Users\Administrator.PB1501034\microblog\app\__init__.py:32]
2018-10-19 15:00:49,111 INFO: Microblog startup [in C:\Users\Administrator.PB1501034\microblog\app\__init__.py:32]
2018-10-19 15:01:16,451 INFO: Microblog startup [in C:\Users\Administrator.PB1501034\microblog\app\__init__.py:32]
